import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from datetime import datetime

disease_mapping = {
    "panic disorder" : 0,
    "vocal cord polyp" : 1,
    "turner syndrome" : 2,
    "cryptorchidism" : 3,
    "poisoning due to ethylene glycol" : 4,
    "atrophic vaginitis" : 5,
    "fracture of the hand" : 6,
    "cellulitis or abscess of mouth" : 7,
    "eye alignment disorder" : 8,
    "headache after lumbar puncture" : 9,
    "pyloric stenosis" : 10,
    "salivary gland disorder" : 11,
    "osteochondrosis" : 12,
    "injury to the knee" : 13,
    "metabolic disorder" : 14,
    "vaginitis" : 15,
    "sick sinus syndrome" : 16,
    "tinnitus of unknown cause" : 17,
    "glaucoma" : 18,
    "eating disorder" : 19,
    "transient ischemic attack" : 20,
    "pyelonephritis" : 21,
    "rotator cuff injury" : 22,
    "chronic pain disorder" : 23,
    "problem during pregnancy" : 24,
    "liver cancer" : 25,
    "atelectasis" : 26,
    "injury to the hand" : 27,
    "choledocholithiasis" : 28,
    "injury to the hip" : 29,
    "cirrhosis" : 30,
    "thoracic aortic aneurysm" : 31,
    "subdural hemorrhage" : 32,
    "diabetic retinopathy" : 33,
    "fibromyalgia" : 34,
    "ischemia of the bowel" : 35,
    "fetal alcohol syndrome" : 36,
    "peritonitis" : 37,
    "injury to the abdomen" : 38,
    "acute pancreatitis" : 39,
    "thrombophlebitis" : 40,
    "asthma" : 41,
    "foreign body in the vagina" : 42,
    "restless leg syndrome" : 43,
    "emphysema" : 44,
    "cysticercosis" : 45,
    "induced abortion" : 46,
    "teething syndrome" : 47,
    "infectious gastroenteritis" : 48,
    "acute sinusitis" : 49,
    "substance-related mental disorder" : 50,
    "postpartum depression" : 51,
    "coronary atherosclerosis" : 52,
    "spondylitis" : 53,
    "pituitary adenoma" : 54,
    "uterine fibroids" : 55,
    "idiopathic nonmenstrual bleeding" : 56,
    "chalazion" : 57,
    "ovarian torsion" : 58,
    "retinopathy due to high blood pressure" : 59,
    "vaginal yeast infection" : 60,
    "mastoiditis" : 61,
    "lung contusion" : 62,
    "hypertrophic obstructive cardiomyopathy (hocm)" : 63,
    "ingrown toe nail" : 64,
    "pulmonary eosinophilia" : 65,
    "corneal disorder" : 66,
    "foreign body in the gastrointestinal tract" : 67,
    "endophthalmitis" : 68,
    "intestinal malabsorption" : 69,
    "viral warts" : 70,
    "hyperhidrosis" : 71,
    "stroke" : 72,
    "pilonidal cyst" : 73,
    "crushing injury" : 74,
    "normal pressure hydrocephalus" : 75,
    "alopecia" : 76,
    "hashimoto thyroiditis" : 77,
    "flat feet" : 78,
    "nonalcoholic liver disease (nash)" : 79,
    "hemarthrosis" : 80,
    "pelvic organ prolapse" : 81,
    "fracture of the arm" : 82,
    "coagulation (bleeding) disorder" : 83,
    "intracranial hemorrhage" : 84,
    "hyperkalemia" : 85,
    "cornea infection" : 86,
    "abscess of the lung" : 87,
    "dengue fever" : 88,
    "chronic sinusitis" : 89,
    "cholesteatoma" : 90,
    "volvulus" : 91,
    "injury to the finger" : 92,
    "poisoning due to analgesics" : 93,
    "atrial fibrillation" : 94,
    "pinworm infection" : 95,
    "urethral valves" : 96,
    "open wound of the neck" : 97,
    "achalasia" : 98,
    "conductive hearing loss" : 99,
    "abdominal hernia" : 100,
    "cerebral palsy" : 101,
    "marijuana abuse" : 102,
    "cryptococcosis" : 103,
    "obesity" : 104,
    "indigestion" : 105,
    "bursitis" : 106,
    "esophageal cancer" : 107,
    "pulmonary congestion" : 108,
    "juvenile rheumatoid arthritis" : 109,
    "actinic keratosis" : 110,
    "acute otitis media" : 111,
    "astigmatism" : 112,
    "tuberous sclerosis" : 113,
    "empyema" : 114,
    "presbyacusis" : 115,
    "neonatal jaundice" : 116,
    "chronic obstructive pulmonary disease (copd)" : 117,
    "dislocation of the elbow" : 118,
    "spondylosis" : 119,
    "herpangina" : 120,
    "injury to the shoulder" : 121,
    "poisoning due to antidepressants" : 122,
    "infection of open wound" : 123,
    "deep vein thrombosis (dvt)" : 124,
    "protein deficiency" : 125,
    "myoclonus" : 126,
    "bone spur of the calcaneous" : 127,
    "von willebrand disease" : 128,
    "open wound of the back" : 129,
    "heart block" : 130,
    "colonic polyp" : 131,
    "magnesium deficiency" : 132,
    "female infertility of unknown cause" : 133,
    "pericarditis" : 134,
    "attention deficit hyperactivity disorder (adhd)" : 135,
    "pulmonic valve disease" : 136,
    "tietze syndrome" : 137,
    "cranial nerve palsy" : 138,
    "injury to the arm" : 139,
    "conversion disorder" : 140,
    "complex regional pain syndrome" : 141,
    "otosclerosis" : 142,
    "injury to the trunk" : 143,
    "hypothyroidism" : 144,
    "primary insomnia" : 145,
    "lice" : 146,
    "vitamin b12 deficiency" : 147,
    "diabetes" : 148,
    "vulvodynia" : 149,
    "endometriosis" : 150,
    "vasculitis" : 151,
    "concussion" : 152,
    "oral leukoplakia" : 153,
    "chronic kidney disease" : 154,
    "bladder disorder" : 155,
    "chorioretinitis" : 156,
    "priapism" : 157,
    "myositis" : 158,
    "mononucleosis" : 159,
    "neuralgia" : 160,
    "polycystic kidney disease" : 161,
    "bipolar disorder" : 162,
    "amyloidosis" : 163,
    "chronic inflammatory demyelinating polyneuropathy (cidp)" : 164,
    "gastroesophageal reflux disease (gerd)" : 165,
    "vitreous hemorrhage" : 166,
    "poisoning due to antimicrobial drugs" : 167,
    "open wound of the mouth" : 168,
    "scleroderma" : 169,
    "myasthenia gravis" : 170,
    "hypoglycemia" : 171,
    "idiopathic absence of menstruation" : 172,
    "dislocation of the ankle" : 173,
    "carbon monoxide poisoning" : 174,
    "panic attack" : 175,
    "plantar fasciitis" : 176,
    "hyperopia" : 177,
    "poisoning due to sedatives" : 178,
    "pemphigus" : 179,
    "peyronie disease" : 180,
    "hiatal hernia" : 181,
    "extrapyramidal effect of drugs" : 182,
    "meniere disease" : 183,
    "anal fissure" : 184,
    "allergy" : 185,
    "chronic otitis media" : 186,
    "fracture of the finger" : 187,
    "hirschsprung disease" : 188,
    "polymyalgia rheumatica" : 189,
    "lymphedema" : 190,
    "bladder cancer" : 191,
    "acute bronchospasm" : 192,
    "acute glaucoma" : 193,
    "open wound of the chest" : 194,
    "dislocation of the patella" : 195,
    "sciatica" : 196,
    "hypercalcemia" : 197,
    "stress incontinence" : 198,
    "varicose veins" : 199,
    "benign kidney cyst" : 200,
    "hydrocele of the testicle" : 201,
    "degenerative disc disease" : 202,
    "hirsutism" : 203,
    "dislocation of the foot" : 204,
    "hydronephrosis" : 205,
    "diverticulosis" : 206,
    "pain after an operation" : 207,
    "huntington disease" : 208,
    "lymphoma" : 209,
    "dermatitis due to sun exposure" : 210,
    "anemia due to chronic kidney disease" : 211,
    "injury to internal organ" : 212,
    "scleritis" : 213,
    "pterygium" : 214,
    "fungal infection of the skin" : 215,
    "insulin overdose" : 216,
    "syndrome of inappropriate secretion of adh (siadh)" : 217,
    "foreign body in the ear" : 218,
    "premenstrual tension syndrome" : 219,
    "orbital cellulitis" : 220,
    "injury to the leg" : 221,
    "hepatic encephalopathy" : 222,
    "bone cancer" : 223,
    "syringomyelia" : 224,
    "pulmonary fibrosis" : 225,
    "mitral valve disease" : 226,
    "parkinson disease" : 227,
    "gout" : 228,
    "otitis media" : 229,
    "drug abuse (opioids)" : 230,
    "myelodysplastic syndrome" : 231,
    "fracture of the shoulder" : 232,
    "acute kidney injury" : 233,
    "threatened pregnancy" : 234,
    "intracranial abscess" : 235,
    "gum disease" : 236,
    "open wound from surgical incision" : 237,
    "gastrointestinal hemorrhage" : 238,
    "seborrheic dermatitis" : 239,
    "drug abuse (methamphetamine)" : 240,
    "torticollis" : 241,
    "poisoning due to antihypertensives" : 242,
    "tension headache" : 243,
    "alcohol intoxication" : 244,
    "scurvy" : 245,
    "narcolepsy" : 246,
    "food allergy" : 247,
    "labyrinthitis" : 248,
    "anxiety" : 249,
    "impulse control disorder" : 250,
    "stenosis of the tear duct" : 251,
    "abscess of nose" : 252,
    "omphalitis" : 253,
    "leukemia" : 254,
    "bell palsy" : 255,
    "conjunctivitis due to allergy" : 256,
    "drug reaction" : 257,
    "adrenal cancer" : 258,
    "myopia" : 259,
    "osteoarthritis" : 260,
    "thyroid disease" : 261,
    "pharyngitis" : 262,
    "chronic rheumatic fever" : 263,
    "hypocalcemia" : 264,
    "macular degeneration" : 265,
    "pneumonia" : 266,
    "cold sore" : 267,
    "premature ventricular contractions (pvcs)" : 268,
    "testicular cancer" : 269,
    "hydrocephalus" : 270,
    "breast cancer" : 271,
    "anemia due to malignancy" : 272,
    "esophageal varices" : 273,
    "endometrial cancer" : 274,
    "cystic fibrosis" : 275,
    "intertrigo (skin condition)" : 276,
    "parathyroid adenoma" : 277,
    "glucocorticoid deficiency" : 278,
    "temporomandibular joint disorder" : 279,
    "wilson disease" : 280,
    "vesicoureteral reflux" : 281,
    "vitamin a deficiency" : 282,
    "gonorrhea" : 283,
    "fracture of the rib" : 284,
    "ependymoma" : 285,
    "hepatitis due to a toxin" : 286,
    "vaginal cyst" : 287,
    "open wound of the shoulder" : 288,
    "ectopic pregnancy" : 289,
    "chronic knee pain" : 290,
    "pinguecula" : 291,
    "hypergammaglobulinemia" : 292,
    "alcohol abuse" : 293,
    "carpal tunnel syndrome" : 294,
    "pituitary disorder" : 295,
    "kidney stone" : 296,
    "autism" : 297,
    "cat scratch disease" : 298,
    "chronic glaucoma" : 299,
    "retinal detachment" : 300,
    "aplastic anemia" : 301,
    "overflow incontinence" : 302,
    "hemolytic anemia" : 303,
    "lateral epicondylitis (tennis elbow)" : 304,
    "open wound of the eye" : 305,
    "syphilis" : 306,
    "diabetic kidney disease" : 307,
    "nose disorder" : 308,
    "drug withdrawal" : 309,
    "dental caries" : 310,
    "hypercholesterolemia" : 311,
    "fracture of the patella" : 312,
    "kidney failure" : 313,
    "fracture of the neck" : 314,
    "muscle spasm" : 315,
    "hemophilia" : 316,
    "hyperosmotic hyperketotic state" : 317,
    "peritonsillar abscess" : 318,
    "gastroparesis" : 319,
    "itching of unknown cause" : 320,
    "polycythemia vera" : 321,
    "thrombocytopenia" : 322,
    "head and neck cancer" : 323,
    "pseudohypoparathyroidism" : 324,
    "goiter" : 325,
    "urge incontinence" : 326,
    "edward syndrome" : 327,
    "open wound of the arm" : 328,
    "muscular dystrophy" : 329,
    "mittelschmerz" : 330,
    "corneal abrasion" : 331,
    "anemia of chronic disease" : 332,
    "dysthymic disorder" : 333,
    "scarlet fever" : 334,
    "hypertensive heart disease" : 335,
    "drug abuse (barbiturates)" : 336,
    "polycystic ovarian syndrome (pcos)" : 337,
    "encephalitis" : 338,
    "cyst of the eyelid" : 339,
    "balanitis" : 340,
    "foreign body in the throat" : 341,
    "drug abuse (cocaine)" : 342,
    "optic neuritis" : 343,
    "alcohol withdrawal" : 344,
    "premature atrial contractions (pacs)" : 345,
    "hemiplegia" : 346,
    "hammer toe" : 347,
    "open wound of the cheek" : 348,
    "joint effusion" : 349,
    "open wound of the knee" : 350,
    "meningioma" : 351,
    "brain cancer" : 352,
    "placental abruption" : 353,
    "seasonal allergies (hay fever)" : 354,
    "lung cancer" : 355,
    "primary kidney disease" : 356,
    "uterine cancer" : 357,
    "dry eye of unknown cause" : 358,
    "fibrocystic breast disease" : 359,
    "fungal infection of the hair" : 360,
    "tooth abscess" : 361,
    "envenomation from spider or animal bite" : 362,
    "vacterl syndrome" : 363,
    "vertebrobasilar insufficiency" : 364,
    "rectal disorder" : 365,
    "atonic bladder" : 366,
    "benign paroxysmal positional vertical (bppv)" : 367,
    "blepharospasm" : 368,
    "sarcoidosis" : 369,
    "metastatic cancer" : 370,
    "trigger finger (finger disorder)" : 371,
    "stye" : 372,
    "hemochromatosis" : 373,
    "osteochondroma" : 374,
    "cushing syndrome" : 375,
    "typhoid fever" : 376,
    "vitreous degeneration" : 377,
    "atrophic skin condition" : 378,
    "aspergillosis" : 379,
    "uterine atony" : 380,
    "trichinosis" : 381,
    "whooping cough" : 382,
    "open wound of the lip" : 383,
    "subacute thyroiditis" : 384,
    "oral mucosal lesion" : 385,
    "open wound due to trauma" : 386,
    "intracerebral hemorrhage" : 387,
    "alzheimer disease" : 388,
    "vaginismus" : 389,
    "systemic lupus erythematosis (sle)" : 390,
    "premature ovarian failure" : 391,
    "thoracic outlet syndrome" : 392,
    "ganglion cyst" : 393,
    "dislocation of the knee" : 394,
    "crohn disease" : 395,
    "postoperative infection" : 396,
    "folate deficiency" : 397,
    "fluid overload" : 398,
    "atrial flutter" : 399,
    "skin disorder" : 400,
    "floaters" : 401,
    "tooth disorder" : 402,
    "heart attack" : 403,
    "open wound of the abdomen" : 404,
    "fracture of the leg" : 405,
    "oral thrush (yeast infection)" : 406,
    "pityriasis rosea" : 407,
    "allergy to animals" : 408,
    "orthostatic hypotension" : 409,
    "obstructive sleep apnea (osa)" : 410,
    "hypokalemia" : 411,
    "psoriasis" : 412,
    "dislocation of the shoulder" : 413,
    "intussusception" : 414,
    "cervicitis" : 415,
    "abscess of the pharynx" : 416,
    "primary thrombocythemia" : 417,
    "arthritis of the hip" : 418,
    "decubitus ulcer" : 419,
    "hypernatremia" : 420,
    "sensorineural hearing loss" : 421,
    "chronic ulcer" : 422,
    "osteoporosis" : 423,
    "ileus" : 424,
    "sickle cell crisis" : 425,
    "urethritis" : 426,
    "prostatitis" : 427,
    "otitis externa (swimmer's ear)" : 428,
    "poisoning due to anticonvulsants" : 429,
    "testicular torsion" : 430,
    "tricuspid valve disease" : 431,
    "urethral stricture" : 432,
    "vitamin d deficiency" : 433,
    "hydatidiform mole" : 434,
    "pain disorder affecting the neck" : 435,
    "tuberculosis" : 436,
    "pelvic fistula" : 437,
    "acute bronchiolitis" : 438,
    "presbyopia" : 439,
    "dementia" : 440,
    "insect bite" : 441,
    "paroxysmal ventricular tachycardia" : 442,
    "congenital heart defect" : 443,
    "connective tissue disorder" : 444,
    "foreign body in the eye" : 445,
    "poisoning due to gas" : 446,
    "pyogenic skin infection" : 447,
    "endometrial hyperplasia" : 448,
    "acanthosis nigricans" : 449,
    "central atherosclerosis" : 450,
    "viral exanthem" : 451,
    "noninfectious gastroenteritis" : 452,
    "benign prostatic hyperplasia (bph)" : 453,
    "menopause" : 454,
    "primary immunodeficiency" : 455,
    "ovarian cancer" : 456,
    "cataract" : 457,
    "dislocation of the hip" : 458,
    "spinal stenosis" : 459,
    "intestinal obstruction" : 460,
    "heart contusion" : 461,
    "congenital malformation syndrome" : 462,
    "sporotrichosis" : 463,
    "lymphangitis" : 464,
    "wernicke korsakoff syndrome" : 465,
    "intestinal disease" : 466,
    "acute bronchitis" : 467,
    "persistent vomiting of unknown cause" : 468,
    "open wound of the foot" : 469,
    "myocarditis" : 470,
    "preeclampsia" : 471,
    "ischemic heart disease" : 472,
    "neurofibromatosis" : 473,
    "chickenpox" : 474,
    "pancreatic cancer" : 475,
    "neuropathy due to drugs" : 476,
    "croup" : 477,
    "idiopathic excessive menstruation" : 478,
    "amblyopia" : 479,
    "meckel diverticulum" : 480,
    "dislocation of the wrist" : 481,
    "ear drum damage" : 482,
    "erectile dysfunction" : 483,
    "temporary or benign blood in urine" : 484,
    "kidney disease due to longstanding hypertension" : 485,
    "chondromalacia of the patella" : 486,
    "onychomycosis" : 487,
    "urethral disorder" : 488,
    "lyme disease" : 489,
    "iron deficiency anemia" : 490,
    "acute respiratory distress syndrome (ards)" : 491,
    "toxic multinodular goiter" : 492,
    "open wound of the finger" : 493,
    "autonomic nervous system disorder" : 494,
    "psychosexual disorder" : 495,
    "anemia" : 496,
    "tendinitis" : 497,
    "common cold" : 498,
    "amyotrophic lateral sclerosis (als)" : 499,
    "central retinal artery or vein occlusion" : 500,
    "paroxysmal supraventricular tachycardia" : 501,
    "venous insufficiency" : 502,
    "trichomonas infection" : 503,
    "acne" : 504,
    "depression" : 505,
    "drug abuse" : 506,
    "urinary tract obstruction" : 507,
    "diabetes insipidus" : 508,
    "iridocyclitis" : 509,
    "varicocele of the testicles" : 510,
    "irritable bowel syndrome" : 511,
    "fracture of the foot" : 512,
    "ovarian cyst" : 513,
    "chlamydia" : 514,
    "parasitic disease" : 515,
    "fracture of the jaw" : 516,
    "lipoma" : 517,
    "female genitalia infection" : 518,
    "pulmonary hypertension" : 519,
    "thyroid nodule" : 520,
    "broken tooth" : 521,
    "dumping syndrome" : 522,
    "lymphadenitis" : 523,
    "injury to the face" : 524,
    "aortic valve disease" : 525,
    "rheumatoid arthritis" : 526,
    "spermatocele" : 527,
    "impetigo" : 528,
    "anal fistula" : 529,
    "hypothermia" : 530,
    "oppositional disorder" : 531,
    "migraine" : 532,
    "diabetic peripheral neuropathy" : 533,
    "testicular disorder" : 534,
    "gestational diabetes" : 535,
    "hidradenitis suppurativa" : 536,
    "valley fever" : 537,
    "conjunctivitis due to bacteria" : 538,
    "lewy body dementia" : 539,
    "multiple myeloma" : 540,
    "head injury" : 541,
    "ascending cholangitis" : 542,
    "idiopathic irregular menstrual cycle" : 543,
    "interstitial lung disease" : 544,
    "mononeuritis" : 545,
    "malaria" : 546,
    "somatization disorder" : 547,
    "hypovolemia" : 548,
    "schizophrenia" : 549,
    "knee ligament or meniscus tear" : 550,
    "endocarditis" : 551,
    "sepsis" : 552,
    "heat stroke" : 553,
    "cholecystitis" : 554,
    "cardiac arrest" : 555,
    "cardiomyopathy" : 556,
    "social phobia" : 557,
    "meningitis" : 558,
    "spherocytosis" : 559,
    "hormone disorder" : 560,
    "raynaud disease" : 561,
    "reactive arthritis" : 562,
    "scabies" : 563,
    "ear wax impaction" : 564,
    "hypertension of pregnancy" : 565,
    "peripheral arterial embolism" : 566,
    "rosacea" : 567,
    "fracture of the skull" : 568,
    "uveitis" : 569,
    "fracture of the facial bones" : 570,
    "tracheitis" : 571,
    "jaw disorder" : 572,
    "perirectal infection" : 573,
    "breast cyst" : 574,
    "post-traumatic stress disorder (ptsd)" : 575,
    "kidney cancer" : 576,
    "vulvar cancer" : 577,
    "blepharitis" : 578,
    "celiac disease" : 579,
    "cystitis" : 580,
    "sickle cell anemia" : 581,
    "subconjunctival hemorrhage" : 582,
    "hemorrhoids" : 583,
    "contact dermatitis" : 584,
    "sinus bradycardia" : 585,
    "high blood pressure" : 586,
    "pelvic inflammatory disease" : 587,
    "liver disease" : 588,
    "chronic constipation" : 589,
    "thyroid cancer" : 590,
    "flu" : 591,
    "friedrich ataxia" : 592,
    "tic (movement) disorder" : 593,
    "skin polyp" : 594,
    "brachial neuritis" : 595,
    "cervical cancer" : 596,
    "adrenal adenoma" : 597,
    "esophagitis" : 598,
    "gas gangrene" : 599,
    "yeast infection" : 600,
    "spina bifida" : 601,
    "drug poisoning due to medication" : 602,
    "alcoholic liver disease" : 603,
    "malignant hypertension" : 604,
    "diverticulitis" : 605,
    "moyamoya disease" : 606,
    "heat exhaustion" : 607,
    "psychotic disorder" : 608,
    "frostbite" : 609,
    "atrophy of the corpus cavernosum" : 610,
    "smoking or tobacco addiction" : 611,
    "sprain or strain" : 612,
    "essential tremor" : 613,
    "open wound of the ear" : 614,
    "foreign body in the nose" : 615,
    "idiopathic painful menstruation" : 616,
    "down syndrome" : 617,
    "idiopathic infrequent menstruation" : 618,
    "pneumothorax" : 619,
    "de quervain disease" : 620,
    "fracture of the vertebra" : 621,
    "human immunodeficiency virus infection (hiv)" : 622,
    "mumps" : 623,
    "subarachnoid hemorrhage" : 624,
    "acute fatty liver of pregnancy (aflp)" : 625,
    "ectropion" : 626,
    "scar" : 627,
    "lactose intolerance" : 628,
    "eustachian tube dysfunction (ear disorder)" : 629,
    "appendicitis" : 630,
    "graves disease" : 631,
    "dissociative disorder" : 632,
    "open wound of the face" : 633,
    "dislocation of the vertebra" : 634,
    "phimosis" : 635,
    "hyperemesis gravidarum" : 636,
    "pregnancy" : 637,
    "thalassemia" : 638,
    "placenta previa" : 639,
    "epidural hemorrhage" : 640,
    "septic arthritis" : 641,
    "athlete's foot" : 642,
    "pleural effusion" : 643,
    "aphakia" : 644,
    "vulvar disorder" : 645,
    "sialoadenitis" : 646,
    "gynecomastia" : 647,
    "urinary tract infection" : 648,
    "histoplasmosis" : 649,
    "erythema multiforme" : 650,
    "scoliosis" : 651,
    "bunion" : 652,
    "arrhythmia" : 653,
    "trigeminal neuralgia" : 654,
    "ankylosing spondylitis" : 655,
    "peripheral nerve disorder" : 656,
    "sebaceous cyst" : 657,
    "poisoning due to antipsychotics" : 658,
    "neurosis" : 659,
    "prostate cancer" : 660,
    "cerebral edema" : 661,
    "dislocation of the finger" : 662,
    "birth trauma" : 663,
    "chronic pancreatitis" : 664,
    "hematoma" : 665,
    "carcinoid syndrome" : 666,
    "open wound of the head" : 667,
    "seborrheic keratosis" : 668,
    "burn" : 669,
    "spontaneous abortion" : 670,
    "genital herpes" : 671,
    "adjustment reaction" : 672,
    "gallstone" : 673,
    "multiple sclerosis" : 674,
    "zenker diverticulum" : 675,
    "fracture of the pelvis" : 676,
    "pneumoconiosis" : 677,
    "hyperlipidemia" : 678,
    "ulcerative colitis" : 679,
    "male genitalia infection" : 680,
    "hpv" : 681,
    "angina" : 682,
    "injury to the spinal cord" : 683,
    "nasal polyp" : 684,
    "lichen simplex" : 685,
    "trichiasis" : 686,
    "acariasis" : 687,
    "colorectal cancer" : 688,
    "skin pigmentation disorder" : 689,
    "factitious disorder" : 690,
    "lymphogranuloma venereum" : 691,
    "galactorrhea of unknown cause" : 692,
    "g6pd enzyme deficiency" : 693,
    "nerve impingement near the shoulder" : 694,
    "toxoplasmosis" : 695,
    "fibroadenoma" : 696,
    "open wound of the hand" : 697,
    "missed abortion" : 698,
    "diabetic ketoacidosis" : 699,
    "granuloma inguinale" : 700,
    "obsessive compulsive disorder (ocd)" : 701,
    "injury of the ankle" : 702,
    "hyponatremia" : 703,
    "stricture of the esophagus" : 704,
    "fracture of the ankle" : 705,
    "soft tissue sarcoma" : 706,
    "bone disorder" : 707,
    "epilepsy" : 708,
    "personality disorder" : 709,
    "shingles (herpes zoster)" : 710,
    "tourette syndrome" : 711,
    "avascular necrosis" : 712,
    "strep throat" : 713,
    "spinocerebellar ataxia" : 714,
    "osteomyelitis" : 715,
    "sjogren syndrome" : 716,
    "adhesive capsulitis of the shoulder" : 717,
    "viral hepatitis" : 718,
    "tonsillar hypertrophy" : 719,
    "gastritis" : 720,
    "skin cancer" : 721,
    "rheumatic fever" : 722,
    "aphthous ulcer" : 723,
    "tonsillitis" : 724,
    "intestinal cancer" : 725,
    "rocky mountain spotted fever" : 726,
    "stomach cancer" : 727,
    "developmental disability" : 728,
    "acute stress reaction" : 729,
    "delirium" : 730,
    "callus" : 731,
    "guillain barre syndrome" : 732,
    "lumbago" : 733,
    "deviated nasal septum" : 734,
    "hemangioma" : 735,
    "peripheral arterial disease" : 736,
    "chronic back pain" : 737,
    "heart failure" : 738,
    "conjunctivitis" : 739,
    "herniated disk" : 740,
    "rhabdomyolysis" : 741,
    "breast infection (mastitis)" : 742,
    "abdominal aortic aneurysm" : 743,
    "pulmonary embolism" : 744,
    "conduct disorder" : 745,
    "mastectomy" : 746,
    "epididymitis" : 747,
    "premature rupture of amniotic membrane" : 748,
    "molluscum contagiosum" : 749,
    "necrotizing fasciitis" : 750,
    "benign vaginal discharge (leukorrhea)" : 751,
    "bladder obstruction" : 752,
    "melanoma" : 753,
    "cervical disorder" : 754,
    "laryngitis" : 755,
    "dyshidrosis" : 756,
    "poisoning due to opioids" : 757,
    "diaper rash" : 758,
    "lichen planus" : 759,
    "gastroduodenal ulcer" : 760,
    "inguinal hernia" : 761,
    "eczema" : 762,
    "asperger syndrome" : 763,
    "mucositis" : 764,
    "paronychia" : 765,
    "open wound of the jaw" : 766,
    "white blood cell disease" : 767,
    "kaposi sarcoma" : 768,
    "spondylolisthesis" : 769,
    "pseudotumor cerebri" : 770,
    "conjunctivitis due to virus" : 771
}

def get_data(path = "./data/training_data.csv", size = 190000):
    file = pd.read_csv(path)
    file["diseases"] = file["diseases"].map(disease_mapping)
    file = file.sample(frac=1)
    X = file.drop("diseases", axis=1).to_numpy()
    Y = file["diseases"].to_numpy().astype(int)
    
    return X[0 : size], Y[0 : size]

X_train, Y_train = get_data(size=197455)
X_test, Y_test = get_data("./data/test_data.csv", size=197455)
print(X_test.shape)
start = datetime.now()

predictor = LogisticRegression(solver="lbfgs", class_weight="balanced")
predictor.fit(X_train, Y_train)

res = predictor.predict(X_test)
print(np.mean(res == Y_test))

end = datetime.now()
print(end - start)