data_info = [
    ('panic disorder', 909),
    ('vocal cord polyp', 90),
    ('turner syndrome', 9),
    ('cryptorchidism', 5),
    ('poisoning due to ethylene glycol', 24),
    ('atrophic vaginitis', 329),
    ('fracture of the hand', 111),
    ('cellulitis or abscess of mouth', 138),
    ('eye alignment disorder', 453),
    ('headache after lumbar puncture', 169),
    ('pyloric stenosis', 16),
    ('salivary gland disorder', 62),
    ('osteochondrosis', 109),
    ('injury to the knee', 53),
    ('metabolic disorder', 34),
    ('vaginitis', 909),
    ('sick sinus syndrome', 158),
    ('tinnitus of unknown cause', 279),
    ('glaucoma', 498),
    ('eating disorder', 494),
    ('transient ischemic attack', 655),
    ('pyelonephritis', 903),
    ('rotator cuff injury', 111),
    ('chronic pain disorder', 677),
    ('problem during pregnancy', 913),
    ('liver cancer', 49),
    ('atelectasis', 99),
    ('injury to the hand', 126),
    ('choledocholithiasis', 441),
    ('injury to the hip', 16),
    ('cirrhosis', 331),
    ('thoracic aortic aneurysm', 168),
    ('subdural hemorrhage', 139),
    ('diabetic retinopathy', 456),
    ('fibromyalgia', 656),
    ('ischemia of the bowel', 283),
    ('fetal alcohol syndrome', 7),
    ('peritonitis', 381),
    ('injury to the abdomen', 64),
    ('acute pancreatitis', 1207),
    ('thrombophlebitis', 451),
    ('asthma', 904),
    ('foreign body in the vagina', 21),
    ('restless leg syndrome', 283),
    ('emphysema', 31),
    ('cysticercosis', 36),
    ('induced abortion', 287),
    ('teething syndrome', 438),
    ('infectious gastroenteritis', 1212),
    ('acute sinusitis', 906),
    ('substance-related mental disorder', 213),
    ('postpartum depression', 494),
    ('coronary atherosclerosis', 112),
    ('spondylitis', 451),
    ('pituitary adenoma', 29),
    ('uterine fibroids', 450),
    ('idiopathic nonmenstrual bleeding', 98),
    ('chalazion', 678),
    ('ovarian torsion', 67),
    ('retinopathy due to high blood pressure', 138),
    ('vaginal yeast infection', 608),
    ('mastoiditis', 144),
    ('lung contusion', 15),
    ('hypertrophic obstructive cardiomyopathy (hocm)', 6),
    ('ingrown toe nail', 604),
    ('pulmonary eosinophilia', 185),
    ('corneal disorder', 676),
    ('foreign body in the gastrointestinal tract', 127),
    ('endophthalmitis', 61),
    ('intestinal malabsorption', 161),
    ('viral warts', 453),
    ('hyperhidrosis', 24),
    ('stroke', 642),
    ('pilonidal cyst', 339),
    ('crushing injury', 63),
    ('normal pressure hydrocephalus', 26),
    ('alopecia', 340),
    ('hashimoto thyroiditis', 12),
    ('flat feet', 33),
    ('nonalcoholic liver disease (nash)', 62),
    ('hemarthrosis', 9),
    ('pelvic organ prolapse', 438),
    ('fracture of the arm', 437),
    ('coagulation (bleeding) disorder', 90),
    ('intracranial hemorrhage', 322),
    ('hyperkalemia', 657),
    ('cornea infection', 903),
    ('abscess of the lung', 19),
    ('dengue fever', 12),
    ('chronic sinusitis', 657),
    ('cholesteatoma', 31),
    ('volvulus', 11),
    ('injury to the finger', 7),
    ('poisoning due to analgesics', 66),
    ('atrial fibrillation', 68),
    ('pinworm infection', 87),
    ('urethral valves', 35),
    ('open wound of the neck', 32),
    ('achalasia', 84),
    ('conductive hearing loss', 598),
    ('abdominal hernia', 407),
    ('cerebral palsy', 139),
    ('marijuana abuse', 1210),
    ('cryptococcosis', 11),
    ('obesity', 18),
    ('indigestion', 447),
    ('bursitis', 1208),
    ('esophageal cancer', 77),
    ('pulmonary congestion', 497),
    ('juvenile rheumatoid arthritis', 33),
    ('actinic keratosis', 909),
    ('acute otitis media', 683),
    ('astigmatism', 321),
    ('tuberous sclerosis', 6),
    ('empyema', 6),
    ('presbyacusis', 55),
    ('neonatal jaundice', 34),
    ('chronic obstructive pulmonary disease (copd)', 906),
    ('dislocation of the elbow', 84),
    ('spondylosis', 1216),
    ('herpangina', 450),
    ('injury to the shoulder', 510),
    ('poisoning due to antidepressants', 29),
    ('infection of open wound', 35),
    ('deep vein thrombosis (dvt)', 240),
    ('protein deficiency', 64),
    ('myoclonus', 11),
    ('bone spur of the calcaneous', 31),
    ('von willebrand disease', 5),
    ('open wound of the back', 9),
    ('heart block', 606),
    ('colonic polyp', 339),
    ('magnesium deficiency', 35),
    ('female infertility of unknown cause', 28),
    ('pericarditis', 147),
    ('attention deficit hyperactivity disorder (adhd)', 507),
    ('pulmonic valve disease', 11),
    ('tietze syndrome', 333),
    ('cranial nerve palsy', 340),
    ('injury to the arm', 1209),
    ('conversion disorder', 20),
    ('complex regional pain syndrome', 1217),
    ('otosclerosis', 19),
    ('injury to the trunk', 905),
    ('hypothyroidism', 74),
    ('primary insomnia', 190),
    ('lice', 65),
    ('vitamin b12 deficiency', 80),
    ('diabetes', 20),
    ('vulvodynia', 1218),
    ('endometriosis', 378),
    ('vasculitis', 299),
    ('concussion', 1191),
    ('oral leukoplakia', 4),
    ('chronic kidney disease', 10),
    ('bladder disorder', 454),
    ('chorioretinitis', 76),
    ('priapism', 6),
    ('myositis', 137),
    ('mononucleosis', 331),
    ('neuralgia', 684),
    ('polycystic kidney disease', 183),
    ('bipolar disorder', 663),
    ('amyloidosis', 4),
    ('chronic inflammatory demyelinating polyneuropathy (cidp)', 18),
    ('gastroesophageal reflux disease (gerd)', 448),
    ('vitreous hemorrhage', 27),
    ('poisoning due to antimicrobial drugs', 97),
    ('open wound of the mouth', 95),
    ('scleroderma', 338),
    ('myasthenia gravis', 134),
    ('hypoglycemia', 1215),
    ('idiopathic absence of menstruation', 493),
    ('dislocation of the ankle', 21),
    ('carbon monoxide poisoning', 88),
    ('panic attack', 188),
    ('plantar fasciitis', 199),
    ('hyperopia', 108),
    ('poisoning due to sedatives', 126),
    ('pemphigus', 7),
    ('peyronie disease', 21),
    ('hiatal hernia', 906),
    ('extrapyramidal effect of drugs', 83),
    ('meniere disease', 281),
    ('anal fissure', 226),
    ('allergy', 905),
    ('chronic otitis media', 669),
    ('fracture of the finger', 8),
    ('hirschsprung disease', 19),
    ('polymyalgia rheumatica', 136),
    ('lymphedema', 505),
    ('bladder cancer', 125),
    ('acute bronchospasm', 906),
    ('acute glaucoma', 210),
    ('open wound of the chest', 6),
    ('dislocation of the patella', 3),
    ('sciatica', 668),
    ('hypercalcemia', 10),
    ('stress incontinence', 255),
    ('varicose veins', 113),
    ('benign kidney cyst', 206),
    ('hydrocele of the testicle', 227),
    ('degenerative disc disease', 909),
    ('hirsutism', 31),
    ('dislocation of the foot', 19),
    ('hydronephrosis', 340),
    ('diverticulosis', 673),
    ('pain after an operation', 908),
    ('huntington disease', 9),
    ('lymphoma', 133),
    ('dermatitis due to sun exposure', 446),
    ('anemia due to chronic kidney disease', 50),
    ('injury to internal organ', 131),
    ('scleritis', 46),
    ('pterygium', 215),
    ('fungal infection of the skin', 683),
    ('insulin overdose', 9),
    ('syndrome of inappropriate secretion of adh (siadh)', 4),
    ('foreign body in the ear', 25),
    ('premenstrual tension syndrome', 137),
    ('orbital cellulitis', 170),
    ('injury to the leg', 1206),
    ('hepatic encephalopathy', 45),
    ('bone cancer', 83),
    ('syringomyelia', 14),
    ('pulmonary fibrosis', 118),
    ('mitral valve disease', 504),
    ('parkinson disease', 513),
    ('gout', 1211),
    ('otitis media', 910),
    ('drug abuse (opioids)', 604),
    ('myelodysplastic syndrome', 3),
    ('fracture of the shoulder', 162),
    ('acute kidney injury', 908),
    ('threatened pregnancy', 905),
    ('intracranial abscess', 12),
    ('gum disease', 894),
    ('open wound from surgical incision', 7),
    ('gastrointestinal hemorrhage', 1214),
    ('seborrheic dermatitis', 880),
    ('drug abuse (methamphetamine)', 330),
    ('torticollis', 280),
    ('poisoning due to antihypertensives', 17),
    ('tension headache', 279),
    ('alcohol intoxication', 351),
    ('scurvy', 4),
    ('narcolepsy', 186),
    ('food allergy', 454),
    ('labyrinthitis', 654),
    ('anxiety', 1198),
    ('impulse control disorder', 335),
    ('stenosis of the tear duct', 102),
    ('abscess of nose', 290),
    ('omphalitis', 7),
    ('leukemia', 10),
    ('bell palsy', 685),
    ('conjunctivitis due to allergy', 1215),
    ('drug reaction', 909),
    ('adrenal cancer', 3),
    ('myopia', 448),
    ('osteoarthritis', 896),
    ('thyroid disease', 17),
    ('pharyngitis', 19),
    ('chronic rheumatic fever', 169),
    ('hypocalcemia', 46),
    ('macular degeneration', 909),
    ('pneumonia', 1212),
    ('cold sore', 192),
    ('premature ventricular contractions (pvcs)', 325),
    ('testicular cancer', 10),
    ('hydrocephalus', 155),
    ('breast cancer', 6),
    ('anemia due to malignancy', 12),
    ('esophageal varices', 3),
    ('endometrial cancer', 88),
    ('cystic fibrosis', 15),
    ('intertrigo (skin condition)', 105),
    ('parathyroid adenoma', 18),
    ('glucocorticoid deficiency', 17),
    ('temporomandibular joint disorder', 341),
    ('wilson disease', 14),
    ('vesicoureteral reflux', 10),
    ('vitamin a deficiency', 5),
    ('gonorrhea', 131),
    ('fracture of the rib', 882),
    ('ependymoma', 19),
    ('hepatitis due to a toxin', 357),
    ('vaginal cyst', 1215),
    ('open wound of the shoulder', 4),
    ('ectopic pregnancy', 341),
    ('chronic knee pain', 150),
    ('pinguecula', 6),
    ('hypergammaglobulinemia', 9),
    ('alcohol abuse', 510),
    ('carpal tunnel syndrome', 896),
    ('pituitary disorder', 30),
    ('kidney stone', 904),
    ('autism', 452),
    ('cat scratch disease', 3),
    ('chronic glaucoma', 668),
    ('retinal detachment', 280),
    ('aplastic anemia', 70),
    ('overflow incontinence', 212),
    ('hemolytic anemia', 27),
    ('lateral epicondylitis (tennis elbow)', 337),
    ('open wound of the eye', 32),
    ('syphilis', 30),
    ('diabetic kidney disease', 2),
    ('nose disorder', 1218),
    ('drug withdrawal', 255),
    ('dental caries', 1185),
    ('hypercholesterolemia', 8),
    ('fracture of the patella', 79),
    ('kidney failure', 282),
    ('fracture of the neck', 41),
    ('muscle spasm', 678),
    ('hemophilia', 21),
    ('hyperosmotic hyperketotic state', 5),
    ('peritonsillar abscess', 246),
    ('gastroparesis', 179),
    ('itching of unknown cause', 504),
    ('polycythemia vera', 49),
    ('thrombocytopenia', 126),
    ('head and neck cancer', 326),
    ('pseudohypoparathyroidism', 12),
    ('goiter', 75),
    ('urge incontinence', 495),
    ('edward syndrome', 6),
    ('open wound of the arm', 10),
    ('muscular dystrophy', 45),
    ('mittelschmerz', 53),
    ('corneal abrasion', 500),
    ('anemia of chronic disease', 40),
    ('dysthymic disorder', 499),
    ('scarlet fever', 90),
    ('hypertensive heart disease', 902),
    ('drug abuse (barbiturates)', 62),
    ('polycystic ovarian syndrome (pcos)', 268),
    ('encephalitis', 94),
    ('cyst of the eyelid', 18),
    ('balanitis', 454),
    ('foreign body in the throat', 156),
    ('drug abuse (cocaine)', 281),
    ('optic neuritis', 10),
    ('alcohol withdrawal', 665),
    ('premature atrial contractions (pacs)', 220),
    ('hemiplegia', 504),
    ('hammer toe', 9),
    ('open wound of the cheek', 10),
    ('joint effusion', 449),
    ('open wound of the knee', 8),
    ('meningioma', 18),
    ('brain cancer', 227),
    ('placental abruption', 14),
    ('seasonal allergies (hay fever)', 910),
    ('lung cancer', 51),
    ('primary kidney disease', 34),
    ('uterine cancer', 5),
    ('dry eye of unknown cause', 861),
    ('fibrocystic breast disease', 14),
    ('fungal infection of the hair', 1212),
    ('tooth abscess', 669),
    ('envenomation from spider or animal bite', 455),
    ('vacterl syndrome', 9),
    ('vertebrobasilar insufficiency', 23),
    ('rectal disorder', 902),
    ('atonic bladder', 71),
    ('benign paroxysmal positional vertical (bppv)', 443),
    ('blepharospasm', 6),
    ('sarcoidosis', 330),
    ('metastatic cancer', 27),
    ('trigger finger (finger disorder)', 87),
    ('stye', 908),
    ('hemochromatosis', 3),
    ('osteochondroma', 211),
    ('cushing syndrome', 9),
    ('typhoid fever', 10),
    ('vitreous degeneration', 341),
    ('atrophic skin condition', 438),
    ('aspergillosis', 10),
    ('uterine atony', 219),
    ('trichinosis', 10),
    ('whooping cough', 43),
    ('open wound of the lip', 26),
    ('subacute thyroiditis', 30),
    ('oral mucosal lesion', 606),
    ('open wound due to trauma', 14),
    ('intracerebral hemorrhage', 603),
    ('alzheimer disease', 336),
    ('vaginismus', 77),
    ('systemic lupus erythematosis (sle)', 159),
    ('premature ovarian failure', 48),
    ('thoracic outlet syndrome', 180),
    ('ganglion cyst', 675),
    ('dislocation of the knee', 3),
    ('crohn disease', 376),
    ('postoperative infection', 111),
    ('folate deficiency', 44),
    ('fluid overload', 327),
    ('atrial flutter', 240),
    ('skin disorder', 676),
    ('floaters', 24),
    ('tooth disorder', 671),
    ('heart attack', 907),
    ('open wound of the abdomen', 3),
    ('fracture of the leg', 678),
    ('oral thrush (yeast infection)', 681),
    ('pityriasis rosea', 71),
    ('allergy to animals', 39),
    ('orthostatic hypotension', 283),
    ('obstructive sleep apnea (osa)', 1196),
    ('hypokalemia', 478),
    ('psoriasis', 912),
    ('dislocation of the shoulder', 64),
    ('intussusception', 4),
    ('cervicitis', 384),
    ('abscess of the pharynx', 341),
    ('primary thrombocythemia', 3),
    ('arthritis of the hip', 1210),
    ('decubitus ulcer', 10),
    ('hypernatremia', 74),
    ('sensorineural hearing loss', 681),
    ('chronic ulcer', 10),
    ('osteoporosis', 378),
    ('ileus', 449),
    ('sickle cell crisis', 913),
    ('urethritis', 453),
    ('prostatitis', 681),
    ("otitis externa (swimmer's ear)", 904),
    ('poisoning due to anticonvulsants', 41),
    ('testicular torsion', 90),
    ('tricuspid valve disease', 9),
    ('urethral stricture', 279),
    ('vitamin d deficiency', 17),
    ('hydatidiform mole', 62),
    ('pain disorder affecting the neck', 387),
    ('tuberculosis', 23),
    ('pelvic fistula', 5),
    ('acute bronchiolitis', 1204),
    ('presbyopia', 212),
    ('dementia', 339),
    ('insect bite', 669),
    ('paroxysmal ventricular tachycardia', 671),
    ('congenital heart defect', 36),
    ('connective tissue disorder', 3),
    ('foreign body in the eye', 281),
    ('poisoning due to gas', 194),
    ('pyogenic skin infection', 911),
    ('endometrial hyperplasia', 49),
    ('acanthosis nigricans', 30),
    ('central atherosclerosis', 18),
    ('viral exanthem', 601),
    ('noninfectious gastroenteritis', 1206),
    ('benign prostatic hyperplasia (bph)', 1206),
    ('menopause', 76),
    ('primary immunodeficiency', 36),
    ('ovarian cancer', 19),
    ('cataract', 607),
    ('dislocation of the hip', 6),
    ('spinal stenosis', 1207),
    ('intestinal obstruction', 445),
    ('heart contusion', 11),
    ('congenital malformation syndrome', 13),
    ('sporotrichosis', 3),
    ('lymphangitis', 3),
    ('wernicke korsakoff syndrome', 6),
    ('intestinal disease', 383),
    ('acute bronchitis', 1213),
    ('persistent vomiting of unknown cause', 186),
    ('open wound of the foot', 27),
    ('myocarditis', 12),
    ('preeclampsia', 217),
    ('ischemic heart disease', 886),
    ('neurofibromatosis', 30),
    ('chickenpox', 104),
    ('pancreatic cancer', 204),
    ('neuropathy due to drugs', 40),
    ('croup', 904),
    ('idiopathic excessive menstruation', 906),
    ('amblyopia', 47),
    ('meckel diverticulum', 4),
    ('dislocation of the wrist', 45),
    ('ear drum damage', 907),
    ('erectile dysfunction', 606),
    ('temporary or benign blood in urine', 897),
    ('kidney disease due to longstanding hypertension', 17),
    ('chondromalacia of the patella', 53),
    ('onychomycosis', 505),
    ('urethral disorder', 315),
    ('lyme disease', 211),
    ('iron deficiency anemia', 683),
    ('acute respiratory distress syndrome (ards)', 451),
    ('toxic multinodular goiter', 79),
    ('open wound of the finger', 4),
    ('autonomic nervous system disorder', 84),
    ('psychosexual disorder', 168),
    ('anemia', 331),
    ('tendinitis', 678),
    ('common cold', 905),
    ('amyotrophic lateral sclerosis (als)', 60),
    ('central retinal artery or vein occlusion', 69),
    ('paroxysmal supraventricular tachycardia', 375),
    ('venous insufficiency', 336),
    ('trichomonas infection', 339),
    ('acne', 496),
    ('depression', 912),
    ('drug abuse', 603),
    ('urinary tract obstruction', 683),
    ('diabetes insipidus', 12),
    ('iridocyclitis', 496),
    ('varicocele of the testicles', 682),
    ('irritable bowel syndrome', 510),
    ('fracture of the foot', 14),
    ('ovarian cyst', 499),
    ('chlamydia', 165),
    ('parasitic disease', 74),
    ('fracture of the jaw', 75),
    ('lipoma', 684),
    ('female genitalia infection', 197),
    ('pulmonary hypertension', 446),
    ('thyroid nodule', 216),
    ('broken tooth', 165),
    ('dumping syndrome', 4),
    ('lymphadenitis', 453),
    ('injury to the face', 455),
    ('aortic valve disease', 451),
    ('rheumatoid arthritis', 678),
    ('spermatocele', 81),
    ('impetigo', 683),
    ('anal fistula', 20),
    ('hypothermia', 13),
    ('oppositional disorder', 431),
    ('migraine', 221),
    ('diabetic peripheral neuropathy', 452),
    ('testicular disorder', 61),
    ('gestational diabetes', 26),
    ('hidradenitis suppurativa', 139),
    ('valley fever', 9),
    ('conjunctivitis due to bacteria', 154),
    ('lewy body dementia', 79),
    ('multiple myeloma', 51),
    ('head injury', 164),
    ('ascending cholangitis', 72),
    ('idiopathic irregular menstrual cycle', 908),
    ('interstitial lung disease', 511),
    ('mononeuritis', 676),
    ('malaria', 15),
    ('somatization disorder', 79),
    ('hypovolemia', 424),
    ('schizophrenia', 890),
    ('knee ligament or meniscus tear', 106),
    ('endocarditis', 83),
    ('sepsis', 909),
    ('heat stroke', 15),
    ('cholecystitis', 1204),
    ('cardiac arrest', 346),
    ('cardiomyopathy', 311),
    ('social phobia', 511),
    ('meningitis', 297),
    ('spherocytosis', 5),
    ('hormone disorder', 55),
    ('raynaud disease', 12),
    ('reactive arthritis', 10),
    ('scabies', 187),
    ('ear wax impaction', 678),
    ('hypertension of pregnancy', 56),
    ('peripheral arterial embolism', 135),
    ('rosacea', 678),
    ('fracture of the skull', 65),
    ('uveitis', 19),
    ('fracture of the facial bones', 449),
    ('tracheitis', 189),
    ('jaw disorder', 336),
    ('perirectal infection', 137),
    ('breast cyst', 22),
    ('post-traumatic stress disorder (ptsd)', 607),
    ('kidney cancer', 80),
    ('vulvar cancer', 6),
    ('blepharitis', 906),
    ('celiac disease', 151),
    ('cystitis', 1219),
    ('sickle cell anemia', 226),
    ('subconjunctival hemorrhage', 249),
    ('hemorrhoids', 908),
    ('contact dermatitis', 909),
    ('sinus bradycardia', 909),
    ('high blood pressure', 15),
    ('pelvic inflammatory disease', 900),
    ('liver disease', 1209),
    ('chronic constipation', 913),
    ('thyroid cancer', 9),
    ('flu', 679),
    ('friedrich ataxia', 5),
    ('tic (movement) disorder', 87),
    ('skin polyp', 897),
    ('brachial neuritis', 907),
    ('cervical cancer', 97),
    ('adrenal adenoma', 35),
    ('esophagitis', 1215),
    ('gas gangrene', 15),
    ('yeast infection', 470),
    ('spina bifida', 82),
    ('drug poisoning due to medication', 208),
    ('alcoholic liver disease', 246),
    ('malignant hypertension', 181),
    ('diverticulitis', 1214),
    ('moyamoya disease', 12),
    ('heat exhaustion', 264),
    ('psychotic disorder', 902),
    ('frostbite', 12),
    ('atrophy of the corpus cavernosum', 47),
    ('smoking or tobacco addiction', 883),
    ('sprain or strain', 1212),
    ('essential tremor', 195),
    ('open wound of the ear', 33),
    ('foreign body in the nose', 14),
    ('idiopathic painful menstruation', 906),
    ('down syndrome', 127),
    ('idiopathic infrequent menstruation', 50),
    ('pneumothorax', 296),
    ('de quervain disease', 92),
    ('fracture of the vertebra', 270),
    ('human immunodeficiency virus infection (hiv)', 2),
    ('mumps', 45),
    ('subarachnoid hemorrhage', 140),
    ('acute fatty liver of pregnancy (aflp)', 9),
    ('ectropion', 38),
    ('scar', 256),
    ('lactose intolerance', 137),
    ('eustachian tube dysfunction (ear disorder)', 909),
    ('appendicitis', 903),
    ('graves disease', 248),
    ('dissociative disorder', 91),
    ('open wound of the face', 3),
    ('dislocation of the vertebra', 38),
    ('phimosis', 60),
    ('hyperemesis gravidarum', 912),
    ('pregnancy', 13),
    ('thalassemia', 16),
    ('placenta previa', 9),
    ('epidural hemorrhage', 10),
    ('septic arthritis', 62),
    ("athlete's foot", 382),
    ('pleural effusion', 607),
    ('aphakia', 9),
    ('vulvar disorder', 160),
    ('sialoadenitis', 509),
    ('gynecomastia', 83),
    ('urinary tract infection', 910),
    ('histoplasmosis', 5),
    ('erythema multiforme', 43),
    ('scoliosis', 171),
    ('bunion', 38),
    ('arrhythmia', 258),
    ('trigeminal neuralgia', 201),
    ('ankylosing spondylitis', 606),
    ('peripheral nerve disorder', 1215),
    ('sebaceous cyst', 913),
    ('poisoning due to antipsychotics', 10),
    ('neurosis', 902),
    ('prostate cancer', 135),
    ('cerebral edema', 104),
    ('dislocation of the finger', 18),
    ('birth trauma', 11),
    ('chronic pancreatitis', 297),
    ('hematoma', 60),
    ('carcinoid syndrome', 2),
    ('open wound of the head', 15),
    ('seborrheic keratosis', 870),
    ('burn', 57),
    ('spontaneous abortion', 1212),
    ('genital herpes', 242),
    ('adjustment reaction', 503),
    ('gallstone', 904),
    ('multiple sclerosis', 910),
    ('zenker diverticulum', 11),
    ('fracture of the pelvis', 184),
    ('pneumoconiosis', 14),
    ('hyperlipidemia', 3),
    ('ulcerative colitis', 377),
    ('male genitalia infection', 138),
    ('hpv', 13),
    ('angina', 906),
    ('injury to the spinal cord', 29),
    ('nasal polyp', 356),
    ('lichen simplex', 59),
    ('trichiasis', 30),
    ('acariasis', 36),
    ('colorectal cancer', 15),
    ('skin pigmentation disorder', 909),
    ('factitious disorder', 13),
    ('lymphogranuloma venereum', 20),
    ('galactorrhea of unknown cause', 11),
    ('g6pd enzyme deficiency', 6),
    ('nerve impingement near the shoulder', 280),
    ('toxoplasmosis', 12),
    ('fibroadenoma', 97),
    ('open wound of the hand', 4),
    ('missed abortion', 375),
    ('diabetic ketoacidosis', 673),
    ('granuloma inguinale', 10),
    ('obsessive compulsive disorder (ocd)', 454),
    ('injury of the ankle', 182),
    ('hyponatremia', 495),
    ('stricture of the esophagus', 86),
    ('fracture of the ankle', 36),
    ('soft tissue sarcoma', 171),
    ('bone disorder', 255),
    ('epilepsy', 75),
    ('personality disorder', 911),
    ('shingles (herpes zoster)', 379),
    ('tourette syndrome', 31),
    ('avascular necrosis', 10),
    ('strep throat', 1210),
    ('spinocerebellar ataxia', 8),
    ('osteomyelitis', 188),
    ('sjogren syndrome', 92),
    ('adhesive capsulitis of the shoulder', 73),
    ('viral hepatitis', 35),
    ('tonsillar hypertrophy', 339),
    ('gastritis', 679),
    ('skin cancer', 661),
    ('rheumatic fever', 2),
    ('aphthous ulcer', 244),
    ('tonsillitis', 446),
    ('intestinal cancer', 49),
    ('rocky mountain spotted fever', 21),
    ('stomach cancer', 155),
    ('developmental disability', 911),
    ('acute stress reaction', 910),
    ('delirium', 598),
    ('callus', 513),
    ('guillain barre syndrome', 57),
    ('lumbago', 156),
    ('deviated nasal septum', 607),
    ('hemangioma', 676),
    ('peripheral arterial disease', 113),
    ('chronic back pain', 899),
    ('heart failure', 903),
    ('conjunctivitis', 909),
    ('herniated disk', 908),
    ('rhabdomyolysis', 16),
    ('breast infection (mastitis)', 501),
    ('abdominal aortic aneurysm', 138),
    ('pulmonary embolism', 880),
    ('conduct disorder', 679),
    ('mastectomy', 17),
    ('epididymitis', 511),
    ('premature rupture of amniotic membrane', 9),
    ('molluscum contagiosum', 511),
    ('necrotizing fasciitis', 3),
    ('benign vaginal discharge (leukorrhea)', 682),
    ('bladder obstruction', 338),
    ('melanoma', 271),
    ('cervical disorder', 43),
    ('laryngitis', 678),
    ('dyshidrosis', 83),
    ('poisoning due to opioids', 9),
    ('diaper rash', 897),
    ('lichen planus', 9),
    ('gastroduodenal ulcer', 683),
    ('inguinal hernia', 402),
    ('eczema', 1207),
    ('asperger syndrome', 338),
    ('mucositis', 289),
    ('paronychia', 438),
    ('open wound of the jaw', 2),
    ('white blood cell disease', 504),
    ('kaposi sarcoma', 24),
    ('spondylolisthesis', 673),
    ('pseudotumor cerebri', 48),
    ('conjunctivitis due to virus', 681)
]

for (d, s) in data_info:
    print(f"(\'{d}\', {s}, \'{d}\'),")
    